### ISSUE TITLE
Could this be added as a PR into animated?

### ISSUE THREAD

**Issue by drcmda** [viewstools/react-dom-animated#1]
@dariocravero Does this work with react 15 as well or is it specifically for react 16? Would you add it as a PR into animated? Brownifed said on Twitter he would merge it.

**Comment by dariocravero** [comment]
I'm using it on React 16 but it should work on both.

I'm a bit tight on time to do a PR now but feel free to take it on if you want to.

I'd love for it to be in, as a matter of fact, I did submit parts in PRs at some stage (and some other code in here is as PRs from other people there too) but they didn't get merged.

This repo has some more stuff than the React 16 update though, as far as I remember it also exports animated components for `a` and `button` and deals with the units when mapping transforms.

**Comment by loganpowell** [comment]
Apparently, they've updated the `animated` library (in 0.2.1) to work with React 16, but I can't get the import to work as it did:

```js
import * as Animated from 'animated/lib/targets/react-dom';
```

Might someone know how to use the new `animated` import?

**Comment by dariocravero** [comment]
Hi @loganpowell, if you install animated locally with npm or yarn you can see the output folder structure and that file is still there. So I figure it should still work. I'm closing this issue and added a note on the README not to use this package anymore as animated is already supporting react 16 which this package was all about, so it fit its purpose :). Of course you can still use it if it works for you but it won't be maintained anymore. See 4f75ffb515245d16d17663791e010ef684527ffe.
